# Generated by Django 2.1.3 on 2018-11-05 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapps', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JopApp',
            new_name='JobApp',
        ),
    ]
